"""Read-only Cloud-OpsBench adoption and corpus-audit contracts.

This package never downloads, mutates, renders, or trains on Cloud-OpsBench.
It preserves the upstream case taxonomy and provenance while producing small
audit summaries for the future 03D split/freeze decision.
"""

from .models import (
    CLOUD_OPSBENCH_REVISION,
    SOURCE_ADAPTER_VERSION,
    CloudOpsBenchCase,
    CloudOpsBenchReferences,
    CloudOpsBenchSource,
    SourceReference,
)
from .scanner import CorpusScan, ScanIssue, scan_corpus
from .taxonomy import (
    UPSTREAM_FAULT_TAXONOMY,
    TaxonomyClassification,
    build_taxonomy_mapping,
    build_taxonomy_report,
)
from .audit import (
    audit_corpus,
    build_context_size_audit,
    build_corpus_census,
    build_golden_trajectory_audit,
    build_real_leakage_audit,
    build_leakage_field_policy,
    build_modality_availability,
    build_split_feasibility,
    build_target_availability,
)
from .training_contract import (
    FREEZE_VERSION,
    MAX_OBSERVATION_CHARS,
    PACKAGING_VERSION,
    TARGET_CONTRACT_VERSION,
    TOOL_CONTRACT_VERSION,
    TRAINING_CONTRACT_VERSION,
    build_duplicate_report,
    build_packaging_audit,
    build_split_manifest,
    build_static_view_manifest,
    build_trajectory_example_manifest,
    freeze_contract,
    model_visible_schema,
    normalize_trajectory,
    packaging_contract,
    sha256_value,
    source_case_derivation_graph,
    source_case_group_id,
    source_manifest_fingerprint,
    split_distribution,
    supervision_policy,
    target_contract,
    tool_contract,
    validate_split_manifest,
)
from .representation_integrity import (
    FALLBACK_REASONS,
    PARITY_CLASSES,
    REPRESENTATION_VERSION,
    classify_fallbacks,
    cumulative_context_audit,
    evidence_retention_summary,
    packaging_omission_audit,
    replay_parity,
    representation_manifest,
    token_budget_projection,
    tool_budget_analysis,
)
from .decomposition import (
    DECOMPOSITION_VERSION,
    build_evidence_package,
    build_evidence_packages,
    build_hierarchy_registry,
    context_size_audit,
    evidence_sufficiency_audit,
    future_record_counts,
    label_support,
    task_contracts,
    trivial_baselines,
)

__all__ = [
    "CLOUD_OPSBENCH_REVISION",
    "SOURCE_ADAPTER_VERSION",
    "CloudOpsBenchCase",
    "CloudOpsBenchReferences",
    "CloudOpsBenchSource",
    "SourceReference",
    "CorpusScan",
    "ScanIssue",
    "scan_corpus",
    "UPSTREAM_FAULT_TAXONOMY",
    "TaxonomyClassification",
    "build_taxonomy_mapping",
    "build_taxonomy_report",
    "audit_corpus",
    "build_context_size_audit",
    "build_corpus_census",
    "build_golden_trajectory_audit",
    "build_real_leakage_audit",
    "build_leakage_field_policy",
    "build_modality_availability",
    "build_split_feasibility",
    "build_target_availability",
    "FREEZE_VERSION",
    "MAX_OBSERVATION_CHARS",
    "PACKAGING_VERSION",
    "TARGET_CONTRACT_VERSION",
    "TOOL_CONTRACT_VERSION",
    "TRAINING_CONTRACT_VERSION",
    "build_duplicate_report",
    "build_packaging_audit",
    "build_split_manifest",
    "build_static_view_manifest",
    "build_trajectory_example_manifest",
    "freeze_contract",
    "model_visible_schema",
    "normalize_trajectory",
    "packaging_contract",
    "sha256_value",
    "source_case_derivation_graph",
    "source_case_group_id",
    "source_manifest_fingerprint",
    "split_distribution",
    "supervision_policy",
    "target_contract",
    "tool_contract",
    "validate_split_manifest",
    "FALLBACK_REASONS",
    "PARITY_CLASSES",
    "REPRESENTATION_VERSION",
    "classify_fallbacks",
    "cumulative_context_audit",
    "evidence_retention_summary",
    "packaging_omission_audit",
    "replay_parity",
    "representation_manifest",
    "token_budget_projection",
    "tool_budget_analysis",
    "DECOMPOSITION_VERSION",
    "build_evidence_package",
    "build_evidence_packages",
    "build_hierarchy_registry",
    "context_size_audit",
    "evidence_sufficiency_audit",
    "future_record_counts",
    "label_support",
    "task_contracts",
    "trivial_baselines",
]
